name: Update Components Submodules

on:
  push:
    branches:
      - dev
  workflow_dispatch:
  workflow_call:

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.DEPLOY_KEY }}

      - name: Update submodules
        run: |
          git submodule update --remote --merge

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '[skip ci] 📦 Update submodules'
          commit_user_name: Zen Browser Robot
          commit_user_email: zen-browser-auto@users.noreply.github.com
